# Generated by Django 2.2.1 on 2019-06-12 08:38

import bbs.save
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='昵称')),
                ('head_img', models.ImageField(default='head/head_img.jfif', storage=bbs.save.newStorage(), unique=True, upload_to='head/%Y%m/', verbose_name='头像')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='3', max_length=2, verbose_name='性别')),
                ('intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='个人介绍')),
                ('wechatimg', models.ImageField(storage=bbs.save.newStorage(), unique=True, upload_to='wechat/%Y%m/', verbose_name='微信二维码')),
                ('website', models.URLField(blank=True, null=True, verbose_name='个人网站')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='关注')),
                ('fans', models.PositiveIntegerField(default=0, verbose_name='粉丝')),
                ('article', models.PositiveIntegerField(default=0, verbose_name='文章')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('loved', models.PositiveIntegerField(default=0, verbose_name='收获喜欢')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息管理',
            },
        ),
    ]
