# Generated by Django 2.2.1 on 2019-06-14 02:39

import bbs.save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20190614_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='wechatimg',
            field=models.ImageField(blank=True, default=None, null=True, storage=bbs.save.newStorage(), unique=True, upload_to='wechat/%Y%m/', verbose_name='微信二维码'),
        ),
    ]
