# Generated by Django 2.2.1 on 2019-06-14 02:41

import bbs.save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20190614_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='wechatimg',
            field=models.ImageField(blank=True, null=True, storage=bbs.save.newStorage(), upload_to='wechat/%Y%m/', verbose_name='微信二维码'),
        ),
    ]
