# Generated by Django 2.2.1 on 2019-06-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0005_auto_20190614_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, max_length=100, verbose_name='摘要')),
                ('have_img', models.ImageField(blank=True, null=True, upload_to='titleimg/%Y%m/', verbose_name='标题图')),
                ('body', models.TextField(verbose_name='文章')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('words', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='评论量')),
                ('love', models.PositiveIntegerField(default=0, verbose_name='喜欢数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('collects', models.ManyToManyField(related_name='collect', to=settings.AUTH_USER_MODEL, verbose_name='收藏')),
                ('loves', models.ManyToManyField(related_name='love', to=settings.AUTH_USER_MODEL, verbose_name='喜欢')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'ordering': ('-created_time',),
            },
        ),
    ]
