# Generated by Django 2.2.1 on 2019-06-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='if_publish',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
    ]
