# Generated by Django 2.2.1 on 2019-07-05 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20190625_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
