# Generated by Django 2.2.1 on 2019-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_comments_commentsreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='artid',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='commentsreply',
            old_name='art_id',
            new_name='article',
        ),
    ]
