# Generated by Django 2.2.1 on 2019-09-18 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0013_auto_20190905_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='thumbsup',
            field=models.ManyToManyField(related_name='up', to=settings.AUTH_USER_MODEL, verbose_name='喜欢'),
        ),
    ]
