# Generated by Django 2.2.1 on 2019-09-18 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0014_comments_thumbsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsreply',
            name='thumbsup',
            field=models.ManyToManyField(related_name='reup', to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='thumbsup',
            field=models.ManyToManyField(related_name='up', to=settings.AUTH_USER_MODEL, verbose_name='点赞'),
        ),
    ]
